### ISSUE TITLE
dr_mp3: would it be possible to use the fast seek at least until the resampler is used for the first time?

### ISSUE THREAD

**Issue by etc0de** [mackron/dr_libs#120]
I read the dr_mp3 code to check if it handles seeking in a fast way, and it seems like the code is kind of there but disabled due to the resampler not liking it. However, I personally feel like a resampler is not a decoder libs job anyway and while I am not suggesting at all to remove the resampler (or at least not as part of this ticket) I bet I'm not the only one who isn't interested in ever using it because I handle it on a higher layer.

For users like me, would it be maybe be possible to re-enable the currently `#if 0`'ed fast seek code in a way that makes it disabled at runtime as soon as the sample rate is ever changed for the first time? So that there is some use for it at least for those people who don't use the resampler anyway, because it's a bit of a shame that it has such an indirect perf impact on otherwise kinda unrelated code.

If this is not feasible then just close this ticket, it was really just a curious thought I had looking at the code.

Edit: sorry, I just realized reading the code more in-depth that the disabled "fast" path doesn't jump over larger sections of the file either, and found confirmation on stackoverflow that indeed mp3 doesn't support fast seek without a precomputed table (with fast seek being like, binary search or similar). So I assume from that the perf impact is only a linear factor and not e.g. exponential? Not as bad as I thought at least

**Comment by mackron** [comment]
I'm actually about to strip out that resampler and replace it with the one I wrote for miniaudio which is much better in basically every way. I'll reassess this when I integrate it. I can't remember the implementation details of seeking + resampling off the top of my head so I'll need to take a proper look when I get a chance.

The main thing that makes seeking with MP3 a bit awkward is that they also don't have running sample counters. A truly general solution that handles MP3 frames with varying sample rates (I don't know how common this is in practice) with an API that uses the concept of a global stream-wide sample rate just requires running everything through a resampler, unfortunately.

The performance impact of the resampler shouldn't be a big deal. It's just a simple linear resampler.

Not sure if it helps, and I expect you may have seen this already, but dr_mp3 does actually support the generation of a seek table:
```
drmp3_calculate_seek_points()
drmp3_bind_seek_table()
```

Also, consider checking out [minimp3_ex](https://github.com/lieff/minimp3/blob/master/minimp3_ex.h). This is an extension to minimp3 which is what dr_mp3 is based on. I haven't used it, so I can't speak for the API's feature set, but I can tell you the base minimp3 library is very good quality. Just skimming the `mp3dec_ex_seek()` function I can see mention of a binary search in there. You could also just use the base minimp3 library, but it's API is a bit awkward as a result of being lower level.

**Comment by etc0de** [comment]
@mackron if a binary search seek is possible, is there any chance it'll ever be added to dr-mp3? Since dr-flac and stb_vorbis also offer this, it seems like the one single thing kinda missing from it.

As for varying sample rates, this might be a radical suggestion but why not just *not* support it? You could also provide a mandatory to-be-implemented resample callback if anybody really wants support for that. The thing with resamplers is not just the added code complexity, but that anything outside libspeex or libsamplerate/libsrc is usually just not that good in quality anyway, so if at all it seems like a basic convenience thing if one doesn't want to plug in a "proper" one. I think it's absolutely excellent miniaudio has a resampler of course, that seems like the right level to do it and less unnecessary code if one decides to not use it, but at the level of each per-file-type decoder lib it just seems a little awkward. **But that's just my own opinion of course.**

Seek tables basically aren't that helpful to me because I'm writing a framework for games where all files are streamed from disk, and I don't know which ones will be played next. So I basically just don't have ever a good time to build them, the current dr-mp3 seek basically requires decoding the entire file and well, so does building a seek table. Both kind of flies into the face of fast disk on-demand disk streaming playback start of a file, sadly.

**Comment by mackron** [comment]
So there's two separate issues being discussed here: the ability to perform more efficient seeking with something like a binary search; and the value of the internal resampler.

Binary searching requires some way to track a running sample count so you can know where you're located in the stream. Unfortunately MP3 frames don't track this information which means you need to track it yourself. dr_mp3's solution is a seektable via the `drmp3_calculate_seek_points()` and `drmp3_bind_seek_table()` APIs, whereas it looks like minimp3_ex builds an index via it's internal `mp3dec_load_index()` API which is called at load time from what I can see (I've only briefly skimmed the minimp3_ex code, so could be more to it). I really can't see a way to do it without some kind of pre-processing step.

The resampler is required because dr_mp3 uses the concept of a per-stream sample rate, whereas MP3 has per-frame sample rates. It therefore requires a resampler to convert those per-frame sample rates to a consistent per-stream sample rate. A question whose answer would be valuable is how frequently this happens in practice. How common is it for an MP3 stream to be made up of frames of varying sample rates? If no known encoder does this then it might be valuable to just strip out the resampler and use the sample rate of the first frame, but I don't have enough data to make this decision.

In terms of resampler quality, the new real-time resampler in miniaudio performs anti-aliasing which improves quality over the existing dr_mp3 resampler which is just a dumb linear interpolation with no filtering. It's still certainly not as good as some other resamplers, but it's acceptable for real-time use, at least to my ears.

By the way, if you pass in 0 as the sample rate in `drmp3_config` it will use the sample rate of the first frame, and if all frames use the same sample rate then I think the resampler will actually just act as an pass-through.

**Comment by etc0de** [comment]
> If no known encoder does

I tried to find this out via google, and only found out that libmad also doesn't support playback of these files, apparently. But yeah, my suspicion would be that it's so rare that it's not worth bothering with.

I'll close this issue anyway, since the faster adhoc-seeking I hoped for isn't possible with mp3, so it's kind of an impossible request :woman_shrugging: thanks for explaining that!

**Comment by krcroft** [comment]
> I'm writing a framework for games where all files are streamed from disk, and I don't know which ones will be played next.

I'm assuming you do have the entire set of mp3's though - correct?  So what you do know, is that at any point in the future these files will be played.

 > So I basically just don't have ever a good time to build them

You have all the time before the user is playing the game. You simply generate the seek tables before hand; and this doesn't have to be during game start-up.  For a given MP3 you only need to generate them once (forever), and save them to files. So the game developers can simply generate the tables prior to shipping and the tables can simply be metadata installed alongside the MP3s.

> kind of flies into the face of fast on-demand disk streaming playback start of a file, sadly

The intent of the seeks tables are much the opposite.  You generate them ahead of time and load them one-time at game startup, _specifically_ to allow fast, on-demand seeking while in-game.

This works great in dosbox-staging, and we don't even know the files ahead of time. Instead, when a user mounts a .cue CDROM image file having mp3 CD-DA tracks, we first look for an existing seek table and if one doesn't exist we generate it on the fly and write it to disk.  DOSBox them starts up, and in-game CD-DA are nearly instant (even faster that other codecs such as Vorbis, FLAC, and Opus).

**Comment by etc0de** [comment]
@krcroft interesting comment! However:

> I'm assuming you do have the entire set of mp3's though - correct?

> You have all the time before the user is playing the game.

I don't, since my framework doesn't currently mandate this, that's up to the user. Specifically, it is a very prototyping-friendly framework made for lua, so there's not a lot of rules and even more so no preprocessing on anything, and that's by design. I could mandate that I know where files are in advance but that would be a quite massive constraint and paradigm shift just to get mp3 seeking so I am not going to do that.

At best I could offer the user to specify a directory optionally preprocess this, but honestly, my current plan is to just not offer seeking for now. It doesn't seem that essential for most types of games. Still, I appreciate your input.

**Comment by krcroft** [comment]
But somehow the user or developer has to connect the mp3s to your framework in the first place.  Be it filenames, or just a bulk directory.  
No matter what, you (the framework) will have an interface to accept mp3s - otherwise your interface won't know what to play.  So whatever that is, you query the mp3s at your frameworks earliest point when it's aware of them, and generate fast seek lookup tables for them, write the tables, and from then on all subsequent seeks will be fast.

This process is extremely fast even on a raspberry pi (over an hour of music processed in less than 5 seconds).  

So you could popup a little "importing tracks" widget, even your environment is so dynamic that users might be drag n' dropping gigabytes of mp3s into the game while in the middle of playing.

**Comment by etc0de** [comment]
The interface is `play this file at /some/dir/bla.mp3` at any point during gameplay, so what you are suggesting **really** doesn't fit into my concept. But thanks for the additional clarification.

**Comment by krcroft** [comment]
Ok; was just trying to help. Opus has excellent seek latency (which is much improved from Xiph's prior speex and vorbis designs), and offers best in class compression as well; so that might be an option.

**Comment by mackron** [comment]
OK, I've written a program to check my library of MP3 files including my test vectors and none exist with different samples rates for any MP3 frames. Considering this, and that the minimp3_ex doesn't do any resampling either, I'm happy to remove the resampling stuff. The same applies to customization of the channel count.

I'm working on changes that will remove the `drmp3_config` object and force everyone to just use the rate and channels reported by the first MP3 frame. This'll greatly simplify the internals of dr_mp3. I should also be able to optimize the linear seek. Should be in this weekend.

**Comment by krcroft** [comment]
Looking forward to this simplification!

**Comment by mackron** [comment]
A preview is in the dev branch now for anybody whose interested to try. See release notes at the top of the file for breaking API changes.

**Comment by krcroft** [comment]
@mackron , good news from my side - the draft FLAC and MP3 revisions are working well in my tests.

**Comment by mackron** [comment]
Thanks for testing! I'll be getting this out in the next few days if all goes well.
