### ISSUE TITLE
dr_mp3 getting frame count is slow

### ISSUE THREAD

**Issue by HookedBehemoth** [mackron/dr_libs#132]
Obtaining the total frame count with drmp3_get_mp3_and_pcm_frame_count or it's two wrappers scans each frame and in my environment this takes ~1 sec per 30 seconds of audio.

Could you think of a way to shortcut this to get a less accurate reading?

mpg123 offers two different calls for getting frame count.
- mpg123_length returns an expected length of current track
- mpg123_scan that scans each frame

**Comment by mackron** [comment]
An entire second for 30 seconds of audio? I just measured it on my computer with a ~3 minute track and I had to loop it 100 times to get it to even take 1 second. I'd be curious to know what environment you're running this on. Is this with optimizations enabled by the way?

Have you measured `mpg123_length` and `mpg123_scan`? How long do they take?

Looking at the dr_mp3 code, this is passing in NULL for the output frames in the decoding function which, I think, should skip the decoding part which should make this quite efficient. Looking at the profiler, though, it looks like I've got an inefficient memmove in there, so maybe that could be contributing? I've improved that a bit in the dev branch (commit https://github.com/mackron/dr_libs/commit/8662eeff8340819f7d2bf3b8e9655cf807aa84de). You able to try that?

By the way, I simplified `drmp3_get_mp3_and_pcm_frame_count()` by removing some old resampling code (dev branch): https://github.com/mackron/dr_libs/commit/ca5865ed7ed05aa0419a3b6946418842c343b0c4

**Comment by HookedBehemoth** [comment]
It's running on the Nintendo switch in the background fighting for CPU time on one core at 1024Mhz on an ARM Cortex a57.

**Comment by HookedBehemoth** [comment]
I didn't disable SIMD if that's what you mean.
Only stdio fwiw.

**Comment by mackron** [comment]
I was more thinking about something like the -O2 option with GCC. If the CPU supports NEON, you may need to explicitly enable it on your compiler (I have no experience with the Nintendo Switch, so not 100% sure). I wouldn't think SIMD should matter too much, though.

FYI, `fread()` consumes 50% of the time in my profiling test.

Curious to know how long `mpg123_length` and `mpg123_scan` take because I'm certainly not seeing any obvious inefficiencies. I don't even know how you'd do a fast approximation.

**Comment by HookedBehemoth** [comment]
O2 on GCC 9.2.0

I'll try my best to get you accurate readings.

**Comment by HookedBehemoth** [comment]
I didn't find a way to get accurate readings on that single thread environment.

I test in "applet mode" now where I can easily print results.

It turns out that I spend **97%** of my time reading the file...

mpg123_tellframe is just this so it takes no time at all.
`off_t attribute_align_arg mpg123_tellframe(mpg123_handle *mh)
{
	if(mh == NULL) return MPG123_ERR;
	if(mh->num < mh->firstframe) return mh->firstframe;
	if(mh->to_decode) return mh->num;
	/* Consider firstoff? */
	return mh->buffer.fill ? mh->num : mh->num + 1;
}`
mpg123_scan does the expected complete scan and takes roughly double the time drmp3_get_pcm_frame_count takes.

**Comment by mackron** [comment]
OK, so `mpg123_length()` is running in constant time which makes sense that it runs so quick. However, it's also just an estimate and is doing things that don't map well with dr_mp3. For one, it looks like perhaps it's reading some tags or something to determine the length at load time?
```
if(mh->track_samples > -1) length = mh->track_samples;
else if(mh->track_frames > 0) length = mh->track_frames*mh->spf;
```
If that's the case, I can't replicate that, at least not right now, as dr_mp3 does not read any kind of tags or metadata. If they're calculating that some other way I'd be curious to know what they're using to determine those values.

The next part is where they do an estimate based on the file size. Unfortunately this won't work with dr_mp3's data feeding abstraction because the length of the stream is not always known at load time (it can support streams of unknown or indefinite length). Therefore it does not have a "size in bytes" to derive the estimate from. And to be honest, I don't even like the idea of using rough estimates like that anyway.

I'm actually pretty happy with that result for the `mpg123_scan()` vs `drmp3_get_pcm_frame_count()` comparison. With the 97% thing, is that just in `fread()`? That's way beyond excessive - I've got a feeling that's including the scanning part of it as well. If it is indeed just in `fread()`, then that's some slow I/O on the Switch.

By the way, are you using `drmp3_init_file()`?

**Comment by HookedBehemoth** [comment]
fread on switch is just an abstraction over the IPC I'm using.

The switch isn't posix and every fread is a call to another service.

I guess this in combination with small buffer sizes and bad random reads on an SD card add up to long scan times.

**Comment by mackron** [comment]
It's not ideal, but could you work around it by caching it in memory and using `drmp3_init_memory()` instead? If you could somehow optimize your I/O throughput you could perhaps even implement your own callbacks and use `drmp3_init()`. If the Switch has a native file I/O API, this could be an option (again, never done any programming for the Switch before, so could be completely wrong about that).

Maybe as an experiment you could change the value of `DRMP3_DATA_CHUNK_SIZE`. This controls how much data is read from the file at a time. You can do something like this above your `#define DRMP3_IMPLEMENTATION` line:
```
#define DRMP3_DATA_CHUNK_SIZE 16384*10 /* <-- Customize this. Must be no less than 16384. */
#define DRMP3_IMPLEMENTATION
#include "dr_mp3.h"
```
Note that this will depend on the latest version in the dev branch.

**Comment by HookedBehemoth** [comment]
Did another measurements with stdio and it takes about the same time. In margin of error more time.

**Comment by mackron** [comment]
How do mean? stdio, as in `fread()`?

**Comment by HookedBehemoth** [comment]
Caching the entire file won't be possible as it's running in a very resource limited scenario.

I'm very happy with the memory footprint with dr_libs as I can bundle more formats with better resource handling on a smaller code footprint.
Currently sitting on <700k total memory statically linked.

**Comment by HookedBehemoth** [comment]
yes

**Comment by HookedBehemoth** [comment]
Ok let me try the dev branch now

**Comment by mackron** [comment]
Yeah, I figured caching the entire file could possibly be a problem. Definitely try that `DRMP3_DATA_CHUNK_SIZE` thing, though. Maybe you could adjust that to the point where it's of an acceptable speed.

**Comment by HookedBehemoth** [comment]
Bumping that buffer size by 10 times decreased scan by ~15 times

**Comment by mackron** [comment]
Good result! That will allocate ~160K of memory on the heap for each `drmp3` object - is that acceptable?

**Comment by HookedBehemoth** [comment]
That's fine for me. I'll test around to find a good balance.

Thanks a lot for your help!

**Comment by mackron** [comment]
No problem at all.

**Comment by HookedBehemoth** [comment]
Great thing is that this also boosts seek times putting it close to wav/flac times.

You are awesome!
