### ISSUE TITLE
Error compiling: integer constant is too large for 'long' type

### ISSUE THREAD

**Issue by aking7** [mackron/dr_libs#147]
I had to modify lines 1142-1146, adding `ULL` after the constants, in order to compile this.

```
    return ((n & (drwav_uint64)0xFF00000000000000ULL) >> 56) |
           ((n & (drwav_uint64)0x00FF000000000000ULL) >> 40) |
           ((n & (drwav_uint64)0x0000FF0000000000ULL) >> 24) |
           ((n & (drwav_uint64)0x000000FF00000000ULL) >>  8) |
```

**Comment by mackron** [comment]
Thanks for the report. This should be fixed in the dev branch now. Are you able to confirm that's working for you? I'll also need to update dr_flac.

I ended up doing a slightly different solution to your proposal due to some C89 compatibility issues: 3cbf05f6463cae5634467c41dd7ad3c0d12db65f

What's your compiler by the way? Surprised to have hit this code path.

**Comment by aking7** [comment]
I can try to check later, but I'm compiling in Cadence Xtensa Xplorer using xt-clang for an embedded platform.

**Comment by mackron** [comment]
I've gone ahead and released this. Thanks for the report!
