### ISSUE TITLE
dr_flac: avoid malloc/free

### ISSUE THREAD

**Issue by kieselsteini** [mackron/dr_libs#17]
Hi there.
I'm appreciate your work you've done with dr_flac. It works like a charm (that's the reason I used it in the example for sts_mixer).

But here's my proposal: please modify drflac_open_* that it takes a pointer to a user allocated drflac structure and initializes it during the opening process. Your internal buffers are also included in this structure. This would save us from an additional (unneeded) malloc. Especially if you need drflac only for a one-shot decoding, it would be easier to store it on the stack.

**Comment by mackron** [comment]
Thanks for the suggestion. Indeed, I had previously experimented with a malloc-less implementation, but I abandoned the idea for a few reasons which I'll take the time to explain for the record.

The first issue is that the drflac* allocation it's actually a dynamically sized allocation of sizeof(drflac) + some extra bytes which is based on the size of the largest frame in the FLAC stream. The size of the largest frame is equal to the number of channels multiplied by the maximum block size. There can be a maximum channel count of 8 and a maximum block size of 65535 which means a potential worst case allocation size of 8 * 65535 * sizeof(int32_t) = 2,097,120 bytes (~2MB). Clearly too much for a stack allocation.

The reason for this kind of allocation scheme is because of performance. The FLAC stream is divided up into frames, and each frame needs to be decoded all at once in order to achieve a reasonable level of performance. Now a large part in keeping drflac easy to use is to allow the client to decode any number of samples at a time, not just whole frames at a time. This means there'll be leftover samples which have not yet been read by drflac_read_*() - they need to be stored somewhere, thus the requirement for that extra allocation.

Of course, there is opportunity for a simplified API for bulk decoding, but that's not the only use case out there, and I'm not very willing to make significant changes to the implementation just to avoid a single malloc.

Hopefully I explained that well enough! Was there a high-level API design you had in mind that won't overly complicate the existing design? I'm planning on making time for doing some work on dr_flac soon, so I'm going to keep this in mind and leave this issue open. Comments and suggestions are most welcome!

**Comment by kieselsteini** [comment]
Thank you for the long and delightful answer. I guess the main reason for asking were two reasons:
a) one shot file decoding - why do I need malloc when I decode a file in one single call
b) stream decoding - place a drflac structure inside another (stream) structure, so there's no need to free 2 separate memory block

But you explained why there's this malloc and I accept it :)

Thanks for all the work you've done.

**Comment by mackron** [comment]
Would an API that looks like this be suitable (should be self-explanatory)?

    int32_t* drflac_open_and_decode_file(
        const char* filename,
        unsigned int* sampleRate,
        unsigned int* channels,
        uint64_t* totalSampleCount);

I can get that done tonight without a problem, but it'll just be a basic wrapper around the existing API to begin with. It'll still use mallocs internally, but I really don't think that'll be a problem because the cost of two mallocs will be dwarfed by the cost of decoding.

(Also, just as a side note, I've got an idea for a new API layer that can avoid internal mallocs, but it'll be a bit longer before I can get that in.)

**Comment by mackron** [comment]
I just added that function because I actually like it now that I've looked at it. Relevant commit is 35f8af67b0e91913b43725219d0953580abdb809 if you care. It's quick and dirty at the moment, but it should work fine for the time being - will optimize it later.

**Comment by kieselsteini** [comment]
You're coding fast :)
