### ISSUE TITLE
[REQ] Set license on GH

### ISSUE THREAD

**Issue by forart** [mackron/dr_libs#197]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [AudioLIBs section](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md)), can you please set licensing terms on this git ?

Thanks in advance !

**Comment by mackron** [comment]
What do you mean exactly? There's already a LICENSE file in the repository if that's what you mean. I can also see the "View license" button on the main page:

![image](https://user-images.githubusercontent.com/1232553/129322867-2150fddb-33e3-4309-8b53-c86ace71430c.png)

I'm suspecting what your issue might be related to is how GitHub doesn't automatically detect the license? I'm think this is due to how I dual license with Unlicense (public domain) and MIT No Attribution. If that's the case, there's nothing I can do to get GitHub to detect it.

**Comment by forart** [comment]
1st of all thanks for the fast reply.

Yes, our "problem" is that not generates the correct label: 

![](https://flat.badgen.net/github/license/mackron/miniaudio?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/mackron/miniaudio?label=LICENSE)

Of course GH doesn't support dual-licensing, but AFAIK it does support Public Domain.

Thanks anyway.

**Comment by mackron** [comment]
There's nothing for me to change here so I'm going to go ahead and close this one.

**Comment by forart** [comment]
Well, unfortunally GH don't support none of the two licenses...

...the unique alternative that is to adopt the [WTFPL](https://choosealicense.com/licenses/wtfpl/) (Do **W**hat **T**he **F***ck You Want To **P**ublic **L**icense) wich is supported instead.

Thanks anyway.
