### ISSUE TITLE
dr_mp3 and minimp3

### ISSUE THREAD

**Issue by ericoporto** [mackron/dr_libs#227]
Hi,

I understand that the code is based on minimp3, looking at them there are indeed even lines of code that are very similar.

Is there anything knew/bugfixed in minimp3 that is worth porting to the code here?

**Comment by mackron** [comment]
Yes, dr_mp3 is just a wrapper around minimp3 so much of the code is identical. I follow the minimp3 project and manually merge changes to keep it all up to date (even non-bug fixes). The stuff in minimp3_ex.h I ignore because that's a separate thing.

Just looking at the latest change in minimp3.h, it looks like I'm up-to-date:

minimp3: https://github.com/lieff/minimp3/commit/ca7c706001331a5a8e3182ce3b3ce3b243589154
dr_mp3: https://github.com/mackron/dr_libs/commit/f092ad9f39c9fdec854bd843afb752389cd6c594

**Comment by ericoporto** [comment]
ah, thanks for the information, just wanted to make sure things are updated. There's an issue in a different project (https://github.com/icculus/SDL_sound/issues/27) and someone just mentioned that the issue was a known problem in minimp3 and I went there to check the code, and the readme really says the issue is a known issue, but the library is consumed from here in the other project. Anyway, just trying to follow the code.
