### ISSUE TITLE
drwav__read_and_close_*() issues

### ISSUE THREAD

**Issue by mednafen** [mackron/dr_libs#23]
https://github.com/mackron/dr_libs/blob/master/dr_wav.h#L1646-L1647
Besides fixing the type, it may be prudent to change the size-checking code to something like:
`if (pWav->totalSampleCount > SIZE_MAX / sizeof(dr_int16)) {`

**Comment by mackron** [comment]
Thanks! I've gone ahead and fixed that, but I've kept the size checking code the same because I like to do the size-in-bytes calculation just the once (for use in both the size check and the input into malloc()), even though I wasn't actually using it in the malloc() call!

Updated in the master branch.
