### ISSUE TITLE
dr_wav - malloc-less implementation option

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [mackron/dr_libs#55]
What do you think about maybe adding a `#define` option to build dr_wav without the functions that use dynamic memory allocation (`DRWAV_MALLOC`, `DRWAV_REALLOC`, `DRWAV_FREE`)? It's preferable to be able to control (or sometimes prevent) dynamic memory allocation, especially in embedded environments.

My cursory review suggest that those macros are only used for the `memory` and `open`/`close` functions, and the `CONVERSION_API`. So without those, you can still `init` (optionally to a `file`), `read` or `write`, and `uninit`.

**Comment by bmcdonnell-ionx** [comment]
You could optionally also e.g. let the user optionally `#define MAX_CONVERSION_SAMPLE_SIZE_BYTES` and use fixed-size buffers on the stack for the `CONVERSION_API`.

**Comment by mackron** [comment]
I'm open to this. It's mainly used in the drwav_open* APIs. I'm actually wondering if I should deprecate and eventually remove `drwav_open()`, `drwav_open_ex()`, `drwav_open_write()`, `drwav_open_write_sequential()` and `drwav_close()` since they are literally identical to the `drwav_init()` versions, only with an added malloc. It's not like it's hard for a program to do their own malloc of the `drwav` structure, and it would also remove a bit of confusion regarding the difference between `init` and `open` which is completely arbitrary.

Then it just leaves `drwav_open_and_read_*()` and `drwav_init_memory_write()` which I can just wrap in a `DRWAV_NO_DYNAMIC_MEMORY` or something.

Where are they used in the `DR_WAV_NO_CONVERSION_API` section by the way? I couldn't see anything in my quick look just now.

**Comment by bmcdonnell-ionx** [comment]
> I'm actually wondering if I should deprecate and eventually remove `drwav_open()`, `drwav_open_ex()`, `drwav_open_write()`, `drwav_open_write_sequential()` and `drwav_close()` since they are literally identical to the `drwav_init()` versions, only with an added malloc. It's not like it's hard for a program to do their own malloc of the `drwav` structure, and it would also remove a bit of confusion regarding the difference between `init` and `open` which is completely arbitrary.

I like this idea. I have experienced that confusion.

I can't think of a need to have the library allocate a `drwav` struct for me, either.

> Then it just leaves `drwav_open_and_read_*()`

and their `pcm_frames_` counterparts,

> and `drwav_init_memory_write()`

and `drwav_free()`,

> which I can just wrap in a `DRWAV_NO_DYNAMIC_MEMORY` or something.

Yup.

> Where are they used in the `DR_WAV_NO_CONVERSION_API` section by the way? I couldn't see anything in my quick look just now.

`drwav__read_and_close_s16()`
`drwav__read_and_close_f32()`
`drwav__read_and_close_s32()`

**Comment by mackron** [comment]
OK, I'll get onto this when I get a chance. Just busy on some closed source stuff at the moment so it may be a little ways away.

**Comment by mackron** [comment]
So I've thought about this one and I've now decided not to go ahead with it. The reason is that now that I think about it, it adds a maintenance cost that I don't think is worthwhile. You can specify your own implementation of `DRWAV_MALLOC`, `DRWAV_REALLOC` and `DRWAV_FREE` which triggers an assert or throws a runtime warning or whatnot. Also, I think it's obvious from the API usage and documentation that `drwav_open_and_read_*()` and `drwav_init_memory_write()` use dynamic allocations internally.

**Comment by bmcdonnell-ionx** [comment]
The value of this option would be in telling the user explicitly when those functions are and are not used, committing (in the interface documentation) to not using them in a subset of the functionality, and enforcing that with the compiler.

I had to poke into the implementation to determine where they were being used, and whether I could safely do without them. Left without this option, a user would need to check each time you make library updates that you don't decide to dynamically allocate memory somewhere that you hadn't before.

> Also, I think it's obvious from the API usage and documentation that `drwav_open_and_read_*()` and `drwav_init_memory_write()` use dynamic allocations internally.

I'm not sure I agree. So maybe it's obvious that those *do*, but the full set of functionality of things which things *don't* is not obvious, IMO.

> it adds a maintenance cost that I don't think is worthwhile.

You already have `DR_WAV_NO_CONVERSION_API` and `DR_WAV_NO_STDIO` `#define` options. How would one more doing the same basic thing add significant complication?

**Comment by mackron** [comment]
> The value of this option would be in telling the user explicitly when those functions are and are not used, committing (in the interface documentation) to not using them in a subset of the functionality, and enforcing that with the compiler.

Where do I draw the line? I'll give you an example. I just recently added support for opening files using `wchar_t*` strings which are Unicode. The normal `char*` APIs are _not_ Unicode, but rather locale-dependent. If had someone submit a request asking that I add an option to disable the `char*` versions because they don't want to accidentally pass a UTF-8 encoded Unicode string to the `char*` version (which, again, does _not_ take a Unicode string), should I accommodate that? My point is that it's not practical for me to accommodate everyone's specific use cases and I need to draw a line somewhere.


> I'm not sure I agree. Even so, maybe it's obvious that those do, but the full set of functionality of things which things don't is not obvious, IMO.

Yep, understand what you're saying. Can than not be addressed through documentation, though? Something like "Unless otherwise noted, no APIs perform dynamic memory allocations."? Though it would depend on me remembering to document it as such when I do add a malloc...


> You already have DR_WAV_NO_CONVERSION_API and DR_WAV_NO_STDIO #define options. How would one more doing the same basic thing add significant complication?

Every option adds a new permutation, and just because it's simple now, doesn't mean it won't have cost implications in the future. For example, I just recently implemented this section of code (which I need to document, now that I think about it) which uses a dynamic memory allocation: https://github.com/mackron/dr_libs/blob/master/dr_wav.h#L1226. That's new code that needs to be handled by this option. That's a cost right there. If I was to forget about handling the option, I would get a bug report about it which then needs to be actioned. There's another cost. It all sounds trivial now, but when your time is limited every time cost matters.

I can't remember my original motivation for `DR_WAV_NO_STDIO`, but most likely it was because the stb libraries did it and I just copied. In any case, this is a standard option in all of my single file libraries so it's staying.

`DR_WAV_NO_CONVERSION_API` was a mistake and I may end up removing it. That's had annoying maintenance issues in the past: https://github.com/mackron/dr_libs/issues/26.

**Comment by bmcdonnell-ionx** [comment]
> Where do I draw the line?

Avoiding or minimizing dynamic memory allocation is very common in embedded applications. From my perspective, this feature is value-added enough that it should be on the other side of the line.

> I'll give you an example. ... If had someone submit a request asking that I add an option to disable the `char*` versions because they don't want to accidentally pass a UTF-8 encoded Unicode string to the `char*` version (which, again, does _not_ take a Unicode string), should I accommodate that?

In that case I'd say no, because the parameter types are explicitly declared and maintained in the interface, and the compiler will warn if a user passes the wrong type of string to it, so there would be no value add AFAICT. This is not analogous.

> > I'm not sure I agree. Even so, maybe it's obvious that those do, but the full set of functionality of things which things don't is not obvious, IMO.
> 
> Yep, understand what you're saying. Can than not be addressed through documentation, though? Something like "Unless otherwise noted, no APIs perform dynamic memory allocations."? Though it would depend on me remembering to document it as such when I do add a malloc...

That's suboptimal, IMO. Also it seems like it would be *more* work to maintain. Implementing this feature with (e.g.) `#define DRWAV_NO_DYNAMIC_MEMORY` at the interface level would allow *you* to use the compiler to maintain such a commitment.

> > You already have DR_WAV_NO_CONVERSION_API and DR_WAV_NO_STDIO #define options. How would one more doing the same basic thing add significant complication?
> 
> Every option adds a new permutation, and just because it's simple now, doesn't mean it won't have cost implications in the future. For example, I just recently implemented this section of code (which I need to document, now that I think about it) which uses a dynamic memory allocation: https://github.com/mackron/dr_libs/blob/master/dr_wav.h#L1226. That's new code that needs to be handled by this option. That's a cost right there. If I was to forget about handling the option, I would get a bug report about it which then needs to be actioned. There's another cost. It all sounds trivial now, but when your time is limited every time cost matters.

With `DRWAV_NO_DYNAMIC_MEMORY`, you'd have a way to use the compiler to remind yourself during your own testing. Without it, you should still eventually get the bug report; it'll just be harder for your users to find the bug.

> `DR_WAV_NO_CONVERSION_API` was a mistake and I may end up removing it. That's had annoying maintenance issues in the past: #26.

I think that option is "nice to have", as a user, if I know I only want to work with the data in its unmodified state, I can explicitly announce and enforce that with the `#define`, and eliminate a sizable portion of the functions I need to be aware of or think about. *However*, I agree that it's not critical, and I wouldn't protest if you remove it.
