### ISSUE TITLE
Minor: underline ==== comments clash with git's merge-conflict identifier

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#70]
When merging code, git by-default will flag merge conflicts using BEFORE and AFTER code blocks separated with a `=======` string:
``` diff
Changes made on the branch that is being merged into. In most cases,
this is the branch that I have currently checked out (i.e. HEAD).
=======
Changes made on the branch that is being merged in. This is often a 
feature/topic branch.
```
If the code itself contains `=======` strings, then this becomes error-prone to edit and search for.  

The recommendation here is (so long as this repo is managed in git) to use ASCII strings that don't overlap with git's identifier lines (perhaps `-------`'s)?

**Comment by mackron** [comment]
Are you talking about the underlines for headers in comments like in this snippet?
```
RELEASE NOTES - v0.12.0
=======================
Version 0.12.0 has breaking API changes including ...
```
I don't particularly want to change this. I'm deliberately using Markdown formatting because I'm planning on doing some automated documentation generation in the future and I just prefer the look of that syntax as opposed to the `#` syntax for headings.

If there's a merge conflict, isn't that something that only I'm going to care about? I wouldn't think other people would be getting a conflict unless they're maintaining their own local changes in a fork, in which case I'm not really interested in explicitly supporting those.

**Comment by krcroft** [comment]
Yes; All good points Dave - you're right, DOSBox doesn't plan on maintaining a separate fork of any dr libs, so makes sense that I won't hit it!
