### ISSUE TITLE
dr_flac: use of potential uninitialized value (GCC 5.x through 9.x warning)

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#93]
GCC 5 - https://github.com/dreamer/dosbox-staging/runs/326319659#step:6:1991
GCC 7 - https://github.com/dreamer/dosbox-staging/runs/326319667#step:6:2017
GCC 9 - https://github.com/dreamer/dosbox-staging/runs/326319675#step:6:2274

```
dr_flac.h: In function ‘drflac__decode_samples_with_residual__rice__scalar’:
dr_flac.h:3212:28: warning: ‘riceParamPart1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             riceParamPart1 &= riceParamMask;
                            ^
dr_flac.h:3211:28: warning: ‘riceParamPart0’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             riceParamPart0 &= riceParamMask;
                            ^
dr_flac.h:3217:47: warning: ‘zeroCountPart1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             riceParamPart1 |= (zeroCountPart1 << riceParam);
                                               ^
dr_flac.h:3216:47: warning: ‘zeroCountPart0’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             riceParamPart0 |= (zeroCountPart0 << riceParam);
                                               ^
dr_flac.h: In function ‘drflac__read_and_decode_metadata’:
dr_flac.h:6152:24: warning: ‘blockSize’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         runningFilePos += blockSize;
```

**Comment by mackron** [comment]
This is only happening when compiling with -Og. I have pushed a workaround to clean these up, but I'm not convinced there was a bug in dr_flac with this. If you look at `blockSize`, you can clearly see that it is always assigned a value and that it's use is guarded by a conditional. I'm questioning whether or not this is a legitimate compiler diagnostic, but then when I tried doing an isolated test I couldn't reproduce it. In any case, should be fixed in the flac/dev branch.

**Comment by krcroft** [comment]
Yes; it does seem impossible that `blockSize` wouldn't be set after that first functional call to `drflac__read_and_decode_block_header`; regardless if it returns TRUE or FALSE.

**Comment by krcroft** [comment]
Fixed!
