### ISSUE TITLE
dr_flac: The 'pFlac' pointer was used unsafely after it was verified against nullptr.

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#97]
![image](https://user-images.githubusercontent.com/1557255/72753716-84e6f980-3b7a-11ea-9f28-daadad7439e6.png)

https://www.viva64.com/en/w/v1004/

**Comment by krcroft** [comment]
This addition checks the pFlac pointer before using it further down in the macro.
```
static type* drflac__full_read_and_close_ ## extension ... 
{ \
    if (pFlac == NULL) { \
        goto on_error; \
    } \
<...>
```

**Comment by mackron** [comment]
I'm not seeing the issue here. I clearly have an assert in place that checks if `pFlac` is NULL here: https://github.com/mackron/dr_libs/blob/0f1fd833b8b9948869b6b3547ac62a33412aaa1b/dr_flac.h#L10367

I don't want to blindly throw a run time check in there because that is an internal API which should always have a valid `pFlac` object passed into it. If it doesn't it means there's a bug at a higher level and I want that assert to get triggered. I also checked all the occurances of `drflac__full_read_and_close_*()` and they are all guarding against the NULL case just fine. Just not seeing this one... Though that doesn't mean there isn't an issue somewhere that I'm just missing...

**Comment by krcroft** [comment]
I agree Dave; and with PVS not providing the path to prove this, my guess is it simply loses the call thread across the macro boundary (or something like that, and just isn't seeing your prior checks).  Will add this to the ignore file.

**Comment by mackron** [comment]
Cool. I'll close this one and set it to will not fix.
